book-app/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('create/', views.BookCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.BookUpdateView.as_view(), name='book_update'),
    path('delete/<int:pk>/', views.BookDeleteView.as_view(), name='book_delete'),
    path('detail/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('', views.BookListView.as_view(), name='book_list'),
]

book-app/tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book-app/book/models.py
from django.db import models
from datetime import datetime    #追加する


class Category(models.Model):
    class Meta:
       #テーブル名の指定
       db_table ="category"
       verbose_name ="カテゴリ"         #追加
       verbose_name_plural ="カテゴリ"  #追加

    #カラム名の定義
    category_name = models.CharField(max_length=255,unique=True)

    def __str__(self):
       return self.category_name


class Book(models.Model):
    class Meta:
       #テーブル名
       db_table ="book"
       verbose_name ="本の登録"          #追加
       verbose_name_plural ="本の登録"   #追加

    # カラムの定義
    title = models.CharField(verbose_name="本のタイトル", max_length=255, help_text="※入力必須項目")
    author = models.CharField(verbose_name="本の著者名", max_length=30, blank=True)
    publisher = models.CharField(verbose_name="本の出版社", max_length=30, blank=True)
    buydate = models.DateField(verbose_name="購入日",default=datetime.now, null=True, blank=True)

    # category = models.ForeignKey(Category, on_delete = models.PROTECT, verbose_name="カテゴリ")
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, verbose_name="カテゴリ", null=True, blank=True)
    url = models.URLField(verbose_name="本のURL（楽天ブックスのURLを入力ください）", max_length=255, help_text="※入力必須項目<br>※重複書籍の登録防止になります", unique=True)

    rental = models.IntegerField(verbose_name="本の貸し出し回数（お手数ですが、貸し出し時に数値をインクリメントください）", blank=True, default=0, help_text="※要望あれば、自動インクリメント機能を実装します")
    email = models.EmailField(verbose_name="本の貸出先E-Mail（本のレンタル時は、E-Mailを入力ください）", max_length=255, blank=True, help_text="※本を返却するときは、E-Mailを削除ください")
    memo = models.TextField(verbose_name="メモ", max_length=255, blank=True)
    comment = models.TextField(verbose_name="本のコメント（書評）", max_length=255, blank=True)

    ########################################################################
    created_at = models.DateTimeField(verbose_name='登録日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    ########################################################################


    def __str__(self):
           return self.title

book-app/book/forms.py
from django import forms
from .models import Book

from django.core.mail import EmailMessage

trans_zen_han = str.maketrans('a', 'b')


class BookForm(forms.ModelForm):
    """
    新規データ登録画面用のフォーム定義
    """
    class Meta:
        model = Book
        fields =['title', 'author','publisher','buydate', 'category', 'url', 'rental', 'email', 'memo', 'comment']
        widgets = {
                'memo': forms.Textarea(attrs={'rows':2, 'cols':15}),
            }

class BookForm2(forms.ModelForm):
    """
    編集データ登録画面用のフォーム定義
    """
    class Meta:
        model = Book
        fields =['title', 'author','publisher','buydate', 'category', 'url', 'rental', 'email', 'memo', 'comment']
        widgets = {
                'memo': forms.Textarea(attrs={'rows':2, 'cols':15}),
            }

book-app/book/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.db import models
from django.contrib import messages

from .models import Category, Book
from .forms import BookForm
from .forms import BookForm2

################################################################
#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class BookListView(ListView):
    #利用するモデルを指定
    model = Book
    #データを渡すテンプレートファイルを指定
    template_name = 'book/book_list.html'

    #家計簿テーブルの全データを取得するメソッドを定義
    def queryset(self):
        return Book.objects.all().order_by('rental').reverse()

################################################################
class BookCreateView(CreateView):
    #利用するモデルを指定
    model = Book
    #データを渡すテンプレートファイルを指定
    template_name = 'book/book_form.html'

    #利用するフォームクラス名を指定
    form_class = BookForm
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('book:book_list')

################################################################
class BookUpdateView(UpdateView):
    #利用するモデルを指定
    model = Book
    #データを渡すテンプレートファイルを指定
    template_name = 'book/book_form2.html'

    #利用するフォームクラス名を指定
    form_class = BookForm2
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('book:book_list')

################################################################
class BookDeleteView(DeleteView):
    #利用するモデルを指定
    model = Book
    #削除処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('book:book_list')

################################################################
class BookDetailView(DetailView):
    #利用するモデルを指定
    model = Book
    #データを渡すテンプレートファイルを指定
    template_name = 'book/book_detail.html'
################################################################

book-app/book/templates/book/base.html
{% load static %}

<!doctype html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Googleフォント用 -->
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">



  <!-- ★linkタグでDataTableのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>

  <!-- linkタグでbootstrapのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

  <!-- オリジナルCSS -->
  <link rel='stylesheet' type="text/css" href="{% static 'style.css' %}">

  <!-- タイトルの設定-->
  <title>Youtube登録アプリ</title>
</head>

<body>
 {% block content %}
  <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
 {% endblock %}

 <!-- bootstrapのjavascrit読み込み-->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>


 <!-- DataTablesのjavascrit読み込み-->
  <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
 <!-- chart.jsの読み込み -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>


 <!-- Databableの定義-->
  <script>
    jQuery(function($){
      // デフォルトの設定を変更
      $.extend( $.fn.dataTable.defaults, {
        language: {
          url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
        }
      });

      $("#book_list").DataTable({
         "searching": true,     //検索機能
         "paging":   true,      //ページング機能
         "ordering": true,      //ソート機能
         "lengthChange": true,  //件数切り替え機能
         order: [ [ 0, "desc" ] ]
         // order: [ [ 0, "asc" ] ]
      }).columns.adjust().draw();

    });
  </script>

</body>
</html>

book-app/book/templates/book/book_confirm_delete.html
{% extends 'book/base.html' %}

{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">

     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'book:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">本の登録アプリ</li>
     </ol>

      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <h3>データ削除</h3>
        </div>
      </div>

      <div class="content-wrapper">
        <div class="container-fluid">
          <p>本名「 {{ object }} 」 のデータを削除していいですか?</p>

          <form method="post">
            <button class="btn btn-danger">削除する</button>
            <a class="btn btn-info" href="{% url 'book:book_list' %}">リストに戻る</a>
             {% csrf_token %}
           </form>
         </div>
       </div>

   </div>
 </div>
{% endblock %}

book-app/book/templates/book/book_detail.html
{% extends 'book/base.html' %}

{% load bootstrap %}
{% block content %}

 <form method="post">
   <div class="container">

     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">

             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'book:book_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">本の登録アプリ</li>
               <li class="breadcrumb-item active">データ動画表示（最近の５件）</li>
             </ol>

            <h3>{{ book.title }}の詳細</h3>

            <div class="table-responsive">
            <table id=book_list width="100%" class="table table-striped table-bordered table-hover">
                <tr>
                  <th>項目</th>
                  <th>値</th>
                </tr>

                <tr>
                  <td>登録日時</td>
                  <td>{{ book.created_at }}</td>
                </tr>
                <tr>
                  <td>更新日時</td>
                  <td>{{ book.updated_at }}</td>
                </tr>
                <tr>
                  <td>タイトル</td>
                  <td>{{ book.title }}</td>
                </tr>
                <tr>
                  <td>著者名</td>
                  <td>{{ book.author }}</td>
                </tr>
                <tr>
                  <td>出版社</td>
                  <td>{{ book.publisher }}</td>
                </tr>
                <tr>
                  <td>購入日</td>
                  <td>{{ book.buydate }}</td>
                </tr>
                <tr>
                  <td>カテゴリ</td>
                  <td>{{ book.category }}</td>
                </tr>
                <tr>
                  <td>本のURL</td>
                  <td>{{ book.url }}</td>
                </tr>
                <tr>
                  <td>本の貸し出し回数</td>
                  <td>{{ book.rental }}</td>
                </tr>
                <tr>
                  <td>貸し出しメールアドレス</td>
                  <td>{{ book.email }}</td>
                </tr>
                <tr>
                  <td>メモ</td>
                  <td>{{ book.memo }}</td>
                </tr>
                <tr>
                  <td>書評コメント</td>
                  <td>{{ book.comment }}</td>
                </tr>
            </table>
            </div>


             <div class="row">
               <div class="col-12">
                 <a class="btn btn-info" href="{% url 'book:book_list' %}">リストに戻る</a>
               </div>
             </div>

          </div>
        </div>
      </div>
   </div>

 </div>
  {% csrf_token %}
</form>


{% endblock %}

book-app/book/templates/book/book_form.html
{% extends 'book/base.html' %}

{% load bootstrap %}
{% block content %}

 <form method="post">
   <div class="container">

     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">

             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'book:book_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">本の登録アプリ</li>
               <li class="breadcrumb-item active">データ登録</li>
             </ol>



             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>データ登録画面</h3>
               </div>
               <div class="card-body">
                 {{ form|bootstrap }}
               </div>
             </div>

             <div class="row">
               <div class="col-12">
                 <button class="btn btn-primary">　保　存　</button>
                 <a class="btn btn-info" href="{% url 'book:book_list' %}">リストに戻る</a>
               </div>
             </div>

          </div>
        </div>
      </div>
   </div>

 </div>
  {% csrf_token %}
</form>


  <!-- ------------------------------------------------ -->
  <br /><br />
   {% if messages %}
   <div class="container">
      <div class="row">
       <div class="my-div-style w-95">
         <ul class="messages" style="list-style: none;">
           {% for message in messages %}
             <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
             </li>
           {% endfor %}
         </ul>
       </div>
     </div>
   </div>
   {% endif %}
   <!-- ------------------------------------------------ -->



{% endblock %}

book-app/book/templates/book/book_form2.html
{% extends 'book/base.html' %}

{% load bootstrap %}
{% block content %}

 <form method="post">
   <div class="container">

     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">

             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'book:book_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">本の登録アプリ</li>
               <li class="breadcrumb-item active">データ更新</li>
             </ol>



             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>データ更新画面</h3>
               </div>
               <div class="card-body">
                 {{ form|bootstrap }}
               </div>
             </div>

             <div class="row">
               <div class="col-12">
                 <button class="btn btn-primary">　保　存　</button>
                 <a class="btn btn-info" href="{% url 'book:book_list' %}">リストに戻る</a>
               </div>
             </div>

          </div>
        </div>
      </div>
   </div>

 </div>
  {% csrf_token %}
</form>


  <!-- ------------------------------------------------ -->
  <br /><br />
   {% if messages %}
   <div class="container">
      <div class="row">
       <div class="my-div-style w-95">
         <ul class="messages" style="list-style: none;">
           {% for message in messages %}
             <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
             </li>
           {% endfor %}
         </ul>
       </div>
     </div>
   </div>
   {% endif %}
   <!-- ------------------------------------------------ -->



{% endblock %}

book-app/book/templates/book/book_list.html
<!-- 親テンプレートを読み込む-->
{% extends 'book/base.html' %}


{% block content %}
<div class="content-wrapper">
  <div class="container-fluid">

  <!-- パンくずリストの設定-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'book:book_list' %}">TOP</a>
    </li>
    <li class="breadcrumb-item active">一覧表示</li>
  </ol>

   <!--ページタイトル-->
   <div class="card mb-3">
     <div class="card-header">
        <h3><b>本の登録アプリ</b></h3>
        <div class="text-right">
          <a class="btn btn-primary btn-lg" href="{% url 'book:create' %}">登録ページ</a>
        </div>
     </div>
     <div class="card-body">

    <div>
       <!-- テーブル表の定義 -->
       <div class="table-responsive">
       <table id=book_list width="100%" class="table table-striped table-bordered table-hover">

           <!-- 表の列の定義-->
           <thead>
             <tr>
              <th class="text-center">登録日時</th>
              <th class="text-center">更新日時</th>

              <th class="text-center">タイトル</th>
              <th class="text-center">著者名</th>
              <th class="text-center">出版社</th>
              <th class="text-center">購入日</th>

              <th class="text-center">カテゴリ</th>
              <th class="text-center">本のURL</th>

              <!-- <th class="text-center">本の貸し出し回数</th>
              <th class="text-center">貸し出しメールアドレス</th> -->
              <th class="text-center">ステータス</th>
              <!-- <th class="text-center">メモ</th> -->
              <th class="text-center">更新・削除</th>
             </tr>
           </thead>
           <!-- ここまでが表の列の定義-->

           <!-- 表のデータ部分の表示-->
           <tbody>
             {% for item in object_list %}
               <tr class="odd gradeX text-center">
                 <td class="text-center" width="100">{{ item.created_at|date:"y/m/d H:i:s" }}</td>
                 <td class="text-center" width="100">{{ item.updated_at|date:"y/m/d H:i:s" }}</td>

                 <td class="text-center" width="140">{{ item.title }}</td>
                 <td class="text-center" width="140">{{ item.author }}</td>
                 <td class="text-center" width="140">{{ item.publisher }}</td>
                 <td class="text-center" width="140">{{ item.buydate }}</td>

                 <td class="text-center" width="100">{{ item.category }}</td>
                 <td class="text-center" width="100"><a href="{{ item.url }}" target="_blank">{{ item.url }}</a></td>

                 <!-- <td class="text-center" width="140">{{ item.rental }}</td>
                 <td class="text-center" width="100">{{ item.email }}</td> -->

                 {% if item.email %}
                 <td class="text-center" width="100">貸し出し中</td>
                 {% else %}
                 <td class="text-center" width="100"></td>
                 {% endif %}

                 <!-- <td class="text-center" width="140">{{ item.memo }}</td>
                 <td class="text-center" width="100">{{ item.comment }}</td> -->

                 <td class="text-center" width="100">
                   <a class="btn btn-primary" href="{% url 'book:book_update' item.pk %}">更新ページ</a>
                   <a class="btn btn-light" href="{% url 'book:book_delete' item.pk %}">削除ページ</a>
                   <a class="btn btn-light" href="{% url 'book:book_detail' item.pk %}" target="_blank">詳細ページ</a>
                 </td>
               </tr>
           {% endfor %}



           </tbody>
           <!-- ここまでが表のデータ部分の表示-->

         </table>
         <!-- ここまでがテーブル表の定義 -->

     </div>
    </div>

    </div>
    </div>



 </div>
</div>


<!-- ----------------------------------------------- -->
<br /><br />
{% if messages %}
<div class="container">
   <div class="row">
    <div class="my-div-style w-100">
      <ul class="messages" style="list-style: none;">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
             {{ message }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endif %}
<!-- ----------------------------------------------- -->


{% endblock content %}